//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CGWork.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CGWorkTYPE                  129
#define IDD_LIGHTS_DLG                  134
#define IDD_MATERIAL_DLG                136
#define IDD_PERS_OPTIONS                139
#define IDD_DRAG_SENSITIVITY_OPTIONS    140
#define IDD_GENERAL_OPTIONS             141
#define IDD_COLOR_OPTIONS               142
#define IDD_SPECIAL_DIALOG              143
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_MATERIAL_AMBIENT            1039
#define IDC_MATERIAL_DIFFUSE            1040
#define IDC_MATERIAL_SHININESS          1041
#define IDC_MATERIAL_SPECULAR           1042
#define IDC_SLIDER_CLOSE                1042
#define IDC_SLIDER_D                    1044
#define IDC_SLIDER_FAR                  1045
#define IDC_TRANSLATE_SENSITIVITY       1046
#define IDC_ROTATE_SENSITIVITY          1047
#define IDC_VIEW_DISTANCE2              1047
#define IDC_SCALE_SENSITIVITY           1048
#define IDD_SLIDER_TESSELATION          1049
#define IDD_SLIDER_FOG_FAR              1050
#define IDC_BUTTON_BACKGROUND_COLOR     1051
#define IDD_SLIDER_TESSELATION3         1051
#define IDD_SLIDER_FOG_CLOSE            1051
#define IDC_BUTTON_WIREFRAME_COLOR      1052
#define IDC_AMB_INTENSITY               1052
#define IDC_BUTTON3                     1053
#define IDC_BUTTON_NORMAL_COLOR         1053
#define IDC_SPEC_EXPONENT               1053
#define IDC_BUTTON_BOUNDRY_COLOR        1054
#define IDC_DIFF_INTENSITY              1054
#define IDC_BG_IMG                      1054
#define IDC_EDIT4                       1055
#define IDC_SPEC_INTENSITY              1055
#define IDC_BG_COLOR                    1055
#define IDC_BUTTON_SILHOUETTE_COLOR     1055
#define IDC_BG_COLOR_BTN                1056
#define IDC_BG_IMG_BTN                  1057
#define IDC_RADIO_IMG_REPEAT            1058
#define IDC_BG_COLOR_BTN2               1059
#define IDC_RADIO_IMG_STRETCH           1060
#define IDC_OUT_HEIGHT                  1061
#define IDC_OUT_WIDTH                   1062
#define IDC_CHECK1                      1063
#define IDC_OUT_SIZE                    1063
#define IDC_ORTHOGRAPHIC                1064
#define IDC_STATIC_ORTHO                1064
#define IDC_RADIO_FOG_COLOR             1064
#define IDC_CHECK2                      1065
#define IDC_CHECK_ALWAYSCALC            1065
#define IDC_CHECK_INVERSENORMALS        1066
#define IDC_RADIO_FOG_TRANSPARENT       1067
#define IDC_RADIO_FOG_OFF               1068
#define IDC_SLIDER_MOTIONBLUR           1069
#define IDC_FOG_COLOR_BTN               1071
#define IDC_COMBO_AA_TYPE               1072
#define IDC_COMBO2                      1073
#define IDC_COMBO_AA_SIZE               1073
#define IDC_ORTHOGRAPHIC_SIZE           2045
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_AXIS_XY                      32801
#define ID_AXIS_BOUNDXYZ                32802
#define ID_OPTIONS_COLOURS              32804
#define ID_OPTIONS_GENERAL              32805
#define ID_OPTIONS_COLORS               32806
#define ID_BUTTON32807                  32807
#define ID_VIEW_SHOWNORMALS             32808
#define ID_VIEW_SHOWBOUNDINGBOX         32809
#define ID_VIEW_SHOWPOLYGONNORMALS      32810
#define ID_SHADING_PHONG                32811
#define ID_WORLD_SPACE                  32812
#define ID_BUTTON32813                  32813
#define ID_BUTTON_TO_FILE               32813
#define ID_OBJECT_SPACE                 32814
#define ID_BUTTON_TO_SCREEN             32815
#define ID_VIEW_SHOWSILHOUETTE          32816
#define ID_VIEW_ENABLEBACKFACECULLING   32817
#define ID_NORMALS_REVERSENORMALS       32818
#define ID_NORMALS_SHOWCALCULATEDNORMALS 32819
#define ID_NORMALS_SHOWIMPORTEDNORMALS  32820
#define ID_BUTTON_ALWAYS_RENDER         32827
#define ID_BUTTON_RECORD_TOGGLE         32829
#define ID_BUTTON_REPLAY                32830
#define ID_BUTTON_REPEAT_REPLAY         32831
#define ID_BUTTON_REPLAY_SPEED_HALF     32832
#define ID_BUTTON_REPLAY_SPEED_1        32833
#define ID_BUTTON_REPLAY_SPEED_2        32834
#define ID_BUTTON_REPLAY_SPEED_4        32835
#define ID_BUTTON32837                  32837
#define ID_BUTTON_VIDEO_TOGGLE          32837
#define ID_OPTIONS_SPECIALEFFECT        32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
